# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 22:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_auto_20170806_0009"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unit",
            options={"ordering": ("position",)},
        ),
    ]
